### ISSUE TITLE
Store more than 2 urls?

### ISSUE THREAD

**Issue by MovingGifts** [ipatate/react-router-scroll-memory#1]
With 2 stored urls, when I navigate forward twice, then go back twice, the main view loses the scroll position. Any idea how to get it to work but to store more than 2 urls, say something like 20 and still scroll the the correct position the view was last scrolled to?

**Comment by MovingGifts** [comment]
@ipatate I tried playing around with the code for a few hours but couldn't get it to work. Please help as this may be something easy for you :)

**Comment by ipatate** [comment]
ok, i will add more store url.

**Comment by MovingGifts** [comment]
Awesome, thank you :) I look forward to trying it!

**Comment by ipatate** [comment]
@MovingGifts i published the beta version. You can test with:
`$ npm i react-router-scroll-memory@beta`
i have not tested all browsers for the moment but it works on Explorer11. 
let me know if it works for you as well
