### ISSUE TITLE
Hash anchor links always jump to top of page

### ISSUE THREAD

**Issue by myvagrantlife** [ipatate/react-router-scroll-memory#11]
When updating the route with a hash anchor the page always jumps to the top. Take the following example:

www.mywebsite.com/faq ->
www.mywebsite.com/faq#question1 ->
www.mywebsite.com/faq#question2 ->
www.mywebsite.com/faq#question3

In this case the page location hasn't actually changed.

PR fix to follow

**Comment by ipatate** [comment]
I work on this problem, it's normally good on my branch #13

**Comment by ipatate** [comment]
in version 1.0.4
