### ISSUE TITLE
IE and Edge SCRIPT438: Object doesn't support property or method 'scroll'

### ISSUE THREAD

**Issue by alimdar** [ipatate/react-router-scroll-memory#15]
When using the elementID attribute, IE and Edge browsers throw an error. 
SCRIPT438: Object doesn't support property or method 'scroll'
https://stackoverflow.com/questions/13975922/script438-object-doesnt-support-property-or-method-ie

**Comment by ipatate** [comment]
👍  Thanks for finding the bug. I have corrected the code. Try the beta version with : react-router-scroll-memory@beta

**Comment by ipatate** [comment]
in version 1.0.4

**Comment by alimdar** [comment]
Sorry for the late reply and thanks for the super fast update. 
Just checked everything and it works like a charm. 
Thank you
