### ISSUE TITLE
Navigating from A to B to C to A and then hitting BACK to return to beginning loses scroll

### ISSUE THREAD

**Issue by chwagssd** [ipatate/react-router-scroll-memory#16]
https://github.com/ipatate/react-router-scroll-memory/blob/1cc2689c638cfdec3385e98321506675339502ae/src/utils/utils.js#L31

Using the URL to lookup the scroll position in the history of scrolls (a flat array) makes the behavior of duplicate instances of the same URL unpredictable.

I've seen that if we navigate in the [demo](https://simple-react-app-with-router.stackblitz.io) from:
1. "HOME" - scroll all the way down
2. Click "Link 17"
3. Click "Home" (by default you are at the top)
4. Hit browser BACK
5. Hit browser BACK
    - Expected: "HOME" with state as it was in #1, scrolled all the way down
    - Actual: "HOME" is shown but scrolled to 0,0

I believe the solution is to stop replacing the entry when the URL matches, instead keep an array for each URL, and when it matches pop the most recent one off the array, that way each instance keeps its scroll position independently without affecting previous ones inadvertently.

**Comment by ipatate** [comment]
ok thanks

**Comment by chwagssd** [comment]
Thanks! I checked at https://simple-react-app-with-router.stackblitz.io/ and the behavior there is as expected now. Scrolling down from initial HOME state, then clicking a link, clicking HOME link to get a new instance of state - followed by __back__ 2 times the 1st state is still scrolled down as expected.
