### ISSUE TITLE
It seems to require an undocumented wrapper <div>

### ISSUE THREAD

**Issue by ibc** [ipatate/react-router-scroll-memory#17]
In comparison with [react-router-scroll-4](https://github.com/ytase/react-router-scroll), it seems that **react-router-scroll-memory** comes with some artificial constraints such as requiring a `<div>` (or similar) wrapper.

To be perfectly clear, this works using **react-router-scroll-4**:

```jsx
import React from 'react';
import { BrowserRouter, Switch, Route } from 'react-router-dom';
import { ScrollContext } from 'react-router-scroll-4';

const App = () => (
	<React.Fragment>
		<BrowserRouter>
			<ScrollContext>
				<Switch>
					<!-- routers here -->
				</Switch>
			</ScrollContext>
		</BrowserRouter>

		<Notifications />
		<SnackBar />
	</React.Fragment>
);

render(App, document.getElementById('my-app'));
```

Similar code does NOT work using **react-router-scroll-memory** (it renders absolutely nothing):

```jsx
import React from 'react';
import { BrowserRouter, Switch, Route } from 'react-router-dom';
import ScrollMemory from 'react-router-scroll-memory';

const App = () => (
	<React.Fragment>
		<BrowserRouter>
			<ScrollMemory>
				<Switch>
					<!-- routers here -->
				</Switch>
			</ScrollMemory>
		</BrowserRouter>

		<Notifications />
		<SnackBar />
	</React.Fragment>
);

render(App, document.getElementById('my-app'));
```

**Comment by ipatate** [comment]
react router scroll memory is not a HOC, for use, place just <Scroll Memory /> in <Switch> for catch location. If it is out <Switch>, location is always '/'.

**Comment by ibc** [comment]
Thanks, but I'm not sure I understand your comment. Also, not sure how it's related to the `<div>` container requirement I told about.

**Comment by ipatate** [comment]
yes, the div is required for encapsulate the children's

**Comment by ibc** [comment]
> yes, the div is required for encapsulate the children's

Thanks. And may I know why? As said above `react-router-scroll-4` does not require any artificial container and works fine.

**Comment by ibc** [comment]
Ok, thanks.
