### ISSUE TITLE
Using ConnectedRouter

### ISSUE THREAD

**Issue by jamilifit** [ipatate/react-router-scroll-memory#22]
Is it possible to use this with ConnectedRouter? It seems to work great with BrowserRouter, but unfortunately, I need to have ConnectedRouter. 

Thanks in advance.

**Comment by ipatate** [comment]
hello, i've never try. Normally, i think yes, you can. Say me please, if it works with.

**Comment by jamilifit** [comment]
Hello. Thanks for the reply. Unfortunately, it does not work with ConnectedRouter. It only seems to work with BrowserRouter. I am using ConnectedRouter and it doesn't seem to work correctly.  It does scroll to the top of the page when you switch routes, but unfortunately, it doesn't save the scroll position when you go back.

**Comment by ipatate** [comment]
When you speak of "ConnectedRouter", you speak of https://github.com/supasate/connected-react-router ?

**Comment by jamilifit** [comment]
Sorry for the late response. Yes, that is the one I am using.

**Comment by ipatate** [comment]
no worries, i will watch when i can.

**Comment by jamilifit** [comment]
Thank you!

**Comment by jamilifit** [comment]
Hello, I thought I would check back to see if you have any updates on why it might not be working with ConnectRouter. Thank you!

**Comment by ipatate** [comment]
hello, yes apparently, it's ok with connectedRouter. I have tested on this repository https://github.com/ipatate/test-connected-react-router

**Comment by jamilifit** [comment]
Oh, that's great, thank you so much!

**Comment by jamilifit** [comment]
Thanks again for the repo, and I do see it working with ConnectedRouter. But do you by any chance have any suggestions on how to get it working with hash history?

**Comment by ipatate** [comment]
No sorry, i don't know ConnectedRouter. But you have a object "location" in props with "hash" key. https://github.com/supasate/connected-react-router/blob/master/FAQ.md#how-to-get-the-current-browser-location-url

**Comment by jamilifit** [comment]
Gotcha. Thanks for all your help!
