### ISSUE TITLE
Feature Request: Particitial Component Support

### ISSUE THREAD

**Issue by danialdezfouli** [ipatate/react-router-scroll-memory#3]
I don't want to use it globally.

**Comment by danialdezfouli** [comment]
It's not working
```
<>
<ScrollMemory elementID='screen' location={location} />
<div id='screen'>
...
</div>
</>
```

**Comment by danialdezfouli** [comment]
It's not working
<>
<ScrollMemory elementID='screen' location={location} />
<div id='screen'>
...
</div>
</>

**Comment by ipatate** [comment]
hi, i don't understand your problem.

**Comment by RayPS** [comment]
Same problem here, there is not documentations for the use of `elementID` and `location`.
I've tried to add an elementID but it's not working at all.
```html
<ScrollMemory elementID='list' />
<div id='list'>
```

```css
body {
    overflow: hidden;
}

#list {
    overflow: scroll;
}
```

**Comment by ipatate** [comment]
Hello, the elementID it's for if you use your app inside div or another element. The system keep th scroll of element instead body page. elementID is the ID of wrapper app.
