### ISSUE TITLE
Would like to be able to defer scrolling until after content is loaded

### ISSUE THREAD

**Issue by dyc3** [ipatate/react-router-scroll-memory#32]
In my project, I'm loading content with a fetch and the page's vertical size changes after the content is loaded. Since the scrolling happens right after the route changes, it doesn't always scroll to the right spot.

**Comment by danidre14** [comment]
Just as I feared. Doesn't match my use case.

**Comment by ipatate** [comment]
if your content is loaded after back in history browser, it's not normal. Use cache for avoid request for the same content already visited.
