### ISSUE TITLE
Feature suggestion: enable scroll memory for non-document elements

### ISSUE THREAD

**Issue by joepio** [ipatate/react-router-scroll-memory#6]
The current implementation only works if the top HTML element (body) is used as the scrollable container. The project that I'm working on uses a child div as the main scrollable container. I suggest adding an optional property (e.g. `elementID`) to `ScrollMemory` that targets the main scrollable div. I'll open a PR for this feature.

**Comment by ipatate** [comment]
ok, you want just id="..." attribute on the main div.

**Comment by ipatate** [comment]
ok, merged. 👍
