### ISSUE TITLE
Allow children props

### ISSUE THREAD

**Issue by ncuillery** [ipatate/react-router-scroll-memory#9]
Thanks for the module which is exactly what I was looking for 👍

How about handling `this.props.children` in the render method?

So instead of:
```jsx
  <BrowserRouter>
    <div>
      <ScrollMemory />
      <App />
    </div>
  </BrowserRouter>
```
we could do:
```jsx
  <BrowserRouter>
    <ScrollMemory>
      <App />
    </ScrollMemory>
  </BrowserRouter>
```

**Comment by ipatate** [comment]
initially, I wanted to do that, but finally I chose to make an autonomous component
